### ISSUE TITLE
Issues with Wordpress Plugin

### ISSUE THREAD

**Issue by vincentkoc** [short-pixel-optimizer/shortpixel-web#3]
Wordpress plugin is slowing down WP-Admin pages. Culprit code:

`            setTimeout(function($) {
                ShortPixel.init();
            }, 10000);
`

Error in chrome console:

`VM80:24 Uncaught ReferenceError: ShortPixel is not defined
    at <anonymous>:24:17`

**Comment by short-pixel-optimizer** [comment]
This means the short-pixel.min.js file is not loaded, I wonder why, do you have any idea? Would it be possible to provide a test environment for this, maybe contact the support on shortpixel.com/contact with the test environment info?
Then, I find it strange that it would slow down the WP admin anyway, as it just throws an error and does nothing, what do you think?

**Comment by vincentkoc** [comment]
Issue seemed to be with [Cloudflare's rocket loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-), fixed temporarily using page rules

`*/wp-admin/*`
`Rocket Loader: Off, Cache Level: Bypass`

Is there a github repository for the Wordpress plugin, as the script tag's need to utilise `script-src 'unsafe-eval' 'self' ajax.cloudflare.com;` in order to resolve issues with Cloudflare

**Comment by short-pixel-optimizer** [comment]
@koconder thanks for the suggestion. There is no public github repository for the plugin. The .js is added using the wordpress functions:

`
    wp_register_script('short-pixel', plugins_url('/res/js/short-pixel.min.js',SHORTPIXEL_PLUGIN_FILE), array(), SHORTPIXEL_IMAGE_OPTIMISER_VERSION);
    wp_enqueue_script('short-pixel.min.js');
`

do you know how I could add the parameters you specified? Thanks!
